ALTER TABLE collection_items 
ALTER COLUMN added_at TYPE TIMESTAMP WITH TIME ZONE 
USING added_at AT TIME ZONE 'UTC',
ALTER COLUMN added_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE collections 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE 
USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE collections 
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE 
USING updated_at AT TIME ZONE 'UTC',
ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE 
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE users 
ALTER COLUMN email_confirmation_sent_at TYPE TIMESTAMP WITH TIME ZONE 
USING email_confirmation_sent_at AT TIME ZONE 'UTC';

ALTER TABLE users 
ALTER COLUMN disabled_at TYPE TIMESTAMP WITH TIME ZONE 
USING email_confirmation_sent_at AT TIME ZONE 'UTC';
