ALTER TABLE valsi_subscriptions 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE 
USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE valsi_subscriptions 
ALTER COLUMN unsubscribed_at TYPE TIMESTAMP WITH TIME ZONE 
USING unsubscribed_at AT TIME ZONE 'UTC';

ALTER TABLE definition_versions 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE 
USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_notifications 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE 
USING created_at AT TIME ZONE 'UTC',
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_notifications 
ALTER COLUMN read_at TYPE TIMESTAMP WITH TIME ZONE 
USING read_at AT TIME ZONE 'UTC';

ALTER TABLE user_notifications 
ALTER COLUMN email_sent TYPE TIMESTAMP WITH TIME ZONE 
USING email_sent AT TIME ZONE 'UTC';

