FROM node:24-alpine

ARG USERNAME
ARG UID
ARG GID

RUN apk update && apk add bash

RUN npm install -g pnpm

RUN mkdir -p /home/$USERNAME/.npm

RUN chown -R $UID:$GID /home/$USERNAME

ENV HOME=/home/$USERNAME
