FROM rust:latest

ARG USERNAME
ARG UID
ARG GID

RUN mkdir -p /home/$USERNAME/.cargo

RUN chown -R $UID:$GID /home/$USERNAME

RUN apt-get update && apt-get install -y libgraphite2-dev libharfbuzz-dev
    
ENV HOME=/home/$USERNAME
ENV CARGO_HOME=/home/$USERNAME/.cargo
